/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIExample */

#ifndef _Included_JNIExample
#define _Included_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIExample
 * Method:    SetCallback
 * Signature: (LJNIExample;)V
 */
JNIEXPORT void JNICALL Java_JNIExample_SetCallback
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
